let timer:any=null
let stepping=false
let stopRequested=false
const status={status:'idle',mode:'',param:'',completedAt:'',log:[],progress:{totalArtists:0,processedArtists:0},lastRunSummary:{newAlbums:0,newCandidates:0}}
Page({
 data:{statusBarHeight:20,topbarHeight:64,crawlerStatus:status as any,crawlerTriggering:false,crawlerScheduleEnabled:false,crawlerScheduleInterval:'weekly',metadataSyncing:false,ownershipRepairing:false,crawlerMode:'approved',crawlerParam:'',crawlerProgressPct:0,crawlerNeedsId:false,crawlerIsCloud:true,crawlerPlaceholder:'',crawlerDesc:'云端一键爬取所有已批准 rapper 的全部专辑 + 单曲',crawlerLastLog:'',crawlerLog:[] as string[],crawlerTriggerTime:0,crawlerModes:[{key:'approved',label:'全部已批准',desc:'云端逐张处理所有已批准 rapper 的专辑',needsId:false,cloud:true,placeholder:''},{key:'artist',label:'按艺人ID',desc:'云端收录指定网易云艺人的全部专辑',needsId:true,cloud:true,placeholder:'网易云艺人 ID'},{key:'album',label:'按专辑ID',desc:'云端精确收录单张网易云专辑',needsId:true,cloud:true,placeholder:'网易云专辑 ID'}]},
 onLoad(){const a=getApp<IAppOption>();this.setData({statusBarHeight:a.globalData.statusBarHeight,topbarHeight:a.globalData.topbarHeight})},onShow(){this.poll()},onHide(){this.stop()},onUnload(){this.stop()},onBack(){wx.navigateBack()},
 poll(){this.stop();this.fetch();timer=setInterval(()=>this.fetch(),1200)},stop(){if(timer){clearInterval(timer);timer=null}},
 fetch(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'getStatus'},success:(r:any)=>{const x=r&&r.result&&r.result.status;if(!x)return;const p=x.progress||{};const logs=Array.isArray(x.log)?x.log:(Array.isArray(x.logs)?x.logs:[]);const safe=Object.assign({},status,x,{log:logs,progress:Object.assign({},status.progress,p),lastRunSummary:Object.assign({},status.lastRunSummary,x.lastRunSummary||{})});this.setData({crawlerStatus:safe,crawlerLog:logs,crawlerLastLog:logs[0]||'',crawlerProgressPct:p.totalArtists?Math.round((p.processedArtists||0)/(p.totalArtists||1)*100):0,crawlerScheduleEnabled:!!(x.schedule&&x.schedule.enabled),crawlerScheduleInterval:(x.schedule&&x.schedule.interval)||'weekly'})},fail:(e:any)=>console.error('[crawlerControl:getStatus]',e)})},
 onCrawlerModeTap(e:any){const k=e.currentTarget.dataset.key;const m=(this.data.crawlerModes as any[]).find(x=>x.key===k);if(m)this.setData({crawlerMode:k,crawlerNeedsId:m.needsId,crawlerIsCloud:m.cloud,crawlerPlaceholder:m.placeholder,crawlerDesc:m.desc,crawlerParam:''})},onCrawlerParamInput(e:any){this.setData({crawlerParam:e.detail.value||''})},
 onCrawlerTrigger(){const m=this.data.crawlerMode,p=(this.data.crawlerParam||'').trim();if((m==='artist'||m==='album')&&!/^\d+$/.test(p)){wx.showToast({title:'请输入数字 ID',icon:'none'});return}if(m==='approved'){if(stepping)return;stopRequested=false;this.setData({crawlerTriggering:true,crawlerProgressPct:0,crawlerLog:[]});stepping=true;this.step(true);return}this.setData({crawlerTriggering:true});wx.cloud.callFunction({name:'cloudCrawler',data:{action:m,param:p},success:()=>{this.setData({crawlerTriggering:false});this.fetch()},fail:(e:any)=>{this.setData({crawlerTriggering:false});console.error('[cloudCrawler:fail]',e);wx.showToast({title:'启动失败',icon:'none'})}})},
 step(initialize:boolean){if(stopRequested){stepping=false;this.setData({crawlerTriggering:false});return}wx.cloud.callFunction({name:'crawlerBatch',data:{initialize},success:(r:any)=>{const x=r&&r.result;this.fetch();if(stopRequested){stepping=false;this.setData({crawlerTriggering:false});return}if(!x||!x.success){stepping=false;this.setData({crawlerTriggering:false});wx.showToast({title:(x&&x.error)||'任务失败',icon:'none'});return}if(initialize&&x.status==='running')this.setData({crawlerTriggering:false});if(x.status==='running'&&x.next&&!stopRequested){setTimeout(()=>this.step(false),80);return}stepping=false;this.setData({crawlerTriggering:false});this.fetch()},fail:(e:any)=>{stepping=false;this.setData({crawlerTriggering:false});console.error('[crawlerBatch:fail]',e);wx.showToast({title:'单步任务失败',icon:'none'});this.fetch()}})},
 onCrawlerAbort(){stopRequested=true;stepping=false;this.setData({crawlerTriggering:false});wx.showLoading({title:'正在中止…',mask:true});wx.cloud.callFunction({name:'crawlerControl',data:{action:'abort'},success:(r:any)=>{wx.hideLoading();const x=r&&r.result;if(!x||!x.success)wx.showToast({title:(x&&x.error)||'中止失败',icon:'none'});else wx.showToast({title:'已请求中止',icon:'success'});this.fetch()},fail:(e:any)=>{wx.hideLoading();console.error('[crawlerControl:abort]',e);wx.showToast({title:'中止请求失败',icon:'none'});this.fetch()}})},
 onRepairAlbumOwnership(){if(this.data.ownershipRepairing)return;wx.showModal({title:'修复专辑归属',content:'将按网易云专辑页艺人栏校正所有已收录专辑。确定开始？',confirmText:'开始修复',success:(modal:any)=>{if(!modal.confirm)return;this.setData({ownershipRepairing:true});wx.cloud.callFunction({name:'repairAlbumOwnership',data:{},success:(res:any)=>{const result=res&&res.result;if(result&&result.success)wx.showToast({title:'修复已启动',icon:'success'});else wx.showToast({title:(result&&result.error)||'启动失败',icon:'none'})},fail:()=>wx.showToast({title:'启动失败',icon:'none'}),complete:()=>this.setData({ownershipRepairing:false})})}})},
 onCrawlerClearLog(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'clearLog'},success:()=>this.fetch(),fail:(e:any)=>console.error('[crawlerControl:clearLog]',e)})},onCleanupSingles(){},onSyncArtistMetadata(){},onScheduleToggle(){},onScheduleInterval(){}
})