let _pollTimer: any = null
const EMPTY_STATUS = { status:'idle', mode:'', param:'', abort:false, completedAt:'', progress:{ totalArtists:0, processedArtists:0, albumsFound:0, candidatesFound:0 }, lastRunSummary:{ newAlbums:0, newCandidates:0, errors:[] } }

Page({
  data: {
    statusBarHeight:20, topbarHeight:64,
    crawlerStatus: EMPTY_STATUS as any,
    crawlerLog: [] as string[],
    crawlerTriggering:false, crawlerBatchActive:false,
    crawlerScheduleEnabled:false, crawlerScheduleInterval:'weekly' as 'daily'|'weekly', metadataSyncing:false,
    crawlerMode:'approved' as 'approved'|'artist'|'album'|'fission'|'sync', crawlerParam:'', crawlerProgressPct:0,
    crawlerNeedsId:false, crawlerIsCloud:true, crawlerPlaceholder:'', crawlerDesc:'云端分批爬取所有已批准 rapper 的专辑',
    crawlerModes:[
      {key:'approved',label:'全部已批准',desc:'分批爬取所有已批准 rapper 的专辑，并补全共创艺人归属',needsId:false,cloud:true,placeholder:''},
      {key:'artist',label:'按艺人ID',desc:'云端收录指定网易云艺人的全部专辑',needsId:true,cloud:true,placeholder:'网易云艺人 ID'},
      {key:'album',label:'按专辑ID',desc:'云端精确收录单张网易云专辑',needsId:true,cloud:true,placeholder:'网易云专辑 ID'},
      {key:'fission',label:'裂变发现',desc:'本地：发现新合作艺人（需开电脑）',needsId:false,cloud:false,placeholder:''},
      {key:'sync',label:'同步决定',desc:'本地：同步审核结果（需开电脑）',needsId:false,cloud:false,placeholder:''},
    ],
  },
  onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight})},
  onShow(){this._startPoll()}, onHide(){this._stopPoll()}, onUnload(){this._stopPoll()}, onBack(){wx.navigateBack()},
  _startPoll(interval=2000){this._stopPoll();this._fetchStatus();_pollTimer=setInterval(()=>this._fetchStatus(),interval)},
  _stopPoll(){if(_pollTimer){clearInterval(_pollTimer);_pollTimer=null}},
  _fetchStatus(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'getStatus'},success:(res:any)=>{const result=res&&res.result;if(!result||!result.success)return;const raw=result.status&&typeof result.status==='object'?result.status:{};const status=Object.assign({},EMPTY_STATUS,raw,{progress:Object.assign({},EMPTY_STATUS.progress,raw.progress||{}),lastRunSummary:Object.assign({},EMPTY_STATUS.lastRunSummary,raw.lastRunSummary||{})});const log=Array.isArray(raw.log)?raw.log:(Array.isArray(raw.logs)?raw.logs:[]);const sched=raw.schedule&&typeof raw.schedule==='object'?raw.schedule:{};const p=status.progress;this.setData({crawlerStatus:status,crawlerLog:log,crawlerProgressPct:p.totalArtists?Math.round(Number(p.processedArtists||0)/Number(p.totalArtists)*100):0,crawlerScheduleEnabled:!!sched.enabled,crawlerScheduleInterval:sched.interval||'weekly'})},fail:()=>{})},
  onCrawlerModeTap(e:WechatMiniprogram.TouchEvent){const key=(e.currentTarget.dataset as any).key;const m=this.data.crawlerModes.find((x:any)=>x.key===key);if(!m)return;this.setData({crawlerMode:key,crawlerNeedsId:m.needsId,crawlerIsCloud:m.cloud,crawlerPlaceholder:m.placeholder,crawlerDesc:m.desc,crawlerParam:''})},
  onCrawlerParamInput(e:WechatMiniprogram.Input){this.setData({crawlerParam:e.detail.value||''})},
  onCrawlerTrigger(){if(this.data.crawlerTriggering||this.data.crawlerBatchActive)return;const s=this.data.crawlerStatus;if(s&&(s.status==='running'||s.status==='pending')){wx.showToast({title:'爬虫正在运行中',icon:'none'});return}const mode=this.data.crawlerMode,param=(this.data.crawlerParam||'').trim();if(this.data.crawlerNeedsId&&!/^\d+$/.test(param)){wx.showToast({title:'请输入数字 ID',icon:'none'});return}if(this.data.crawlerIsCloud)this._triggerCloud(mode,param);else this._triggerLocal(mode,param)},
  _runApprovedBatch(cursor=0,initialize=false){wx.cloud.callFunction({name:'crawlerBatch',data:{cursor,initialize},success:(res:any)=>{const r=res&&res.result;if(!r){this.setData({crawlerTriggering:false,crawlerBatchActive:false});wx.showToast({title:'云函数没有返回结果',icon:'none'});return}this._fetchStatus();if(!r.success){this.setData({crawlerTriggering:false,crawlerBatchActive:false});wx.showToast({title:r.error||'批处理失败',icon:'none'});return}if(r.status==='running'&&typeof r.nextCursor==='number'&&this.data.crawlerBatchActive){this.setData({crawlerTriggering:false});setTimeout(()=>this._runApprovedBatch(r.nextCursor,false),600);return}this.setData({crawlerTriggering:false,crawlerBatchActive:false})},fail:(err:any)=>{this.setData({crawlerTriggering:false,crawlerBatchActive:false});const msg=String((err&&err.errMsg)||'云函数调用失败').replace(/^.*?error:\s*/i,'').slice(0,28);wx.showToast({title:msg||'云函数调用失败',icon:'none'});console.error('[crawlerBatch]',err);this._fetchStatus()}})},
  _triggerCloud(mode:string,param:string){if(mode==='approved'){this.setData({crawlerTriggering:true,crawlerBatchActive:true});this._runApprovedBatch(0,true);this._startPoll(1500);wx.showToast({title:'已开始分批处理',icon:'success'});return}const action=mode==='artist'?'artist':'album';this.setData({crawlerTriggering:true});wx.cloud.callFunction({name:'cloudCrawler',data:{action,param},success:(res:any)=>{this.setData({crawlerTriggering:false});const r=res&&res.result||{};wx.showToast({title:r.success?`新增 ${r.inserted||0} 张`:r.error||'爬取失败',icon:r.success?'success':'none'});this._fetchStatus()},fail:()=>{this.setData({crawlerTriggering:false});wx.showToast({title:'网络错误',icon:'error'})}})},
  _triggerLocal(mode:string,param:string){this.setData({crawlerTriggering:true});wx.cloud.callFunction({name:'crawlerControl',data:{action:'trigger',mode,param},success:(res:any)=>{this.setData({crawlerTriggering:false});wx.showToast({title:res&&res.result&&res.result.success?'已触发，等待本地爬虫':'触发失败',icon:res&&res.result&&res.result.success?'success':'error'});this._fetchStatus()},fail:()=>{this.setData({crawlerTriggering:false});wx.showToast({title:'网络错误',icon:'error'})}})},
  onCrawlerAbort(){const s=this.data.crawlerStatus;if(!s||(s.status!=='running'&&s.status!=='pending'))return;wx.showModal({title:'中止爬虫',content:'确定中止当前任务？已写入的数据会保留。',confirmText:'中止',confirmColor:'#C0392B',success:r=>{if(!r.confirm)return;this.setData({crawlerBatchActive:false});wx.cloud.callFunction({name:'crawlerControl',data:{action:'abort'},success:()=>{wx.showToast({title:'已请求中止',icon:'none'});this._fetchStatus()},fail:()=>wx.showToast({title:'网络错误',icon:'error'})})}})},
  onCrawlerClearLog(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'clearLog'},success:()=>{this._fetchStatus();wx.showToast({title:'日志已清除',icon:'success'})}})},
  onCleanupSingles(){wx.showModal({title:'清除单曲',content:'将删除所有曲目数为 1 或 2 的条目，操作不可撤销。',confirmText:'清除',confirmColor:'#C0392B',success:r=>{if(!r.confirm)return;wx.showLoading({title:'清除中…',mask:true});wx.cloud.callFunction({name:'manageCandidates',data:{action:'cleanup_singles'},success:(res:any)=>{wx.hideLoading();const x=res&&res.result||{};wx.showToast({title:x.success?`已删除 ${x.removed} 条`:x.error||'操作失败',icon:x.success?'success':'none'})},fail:()=>{wx.hideLoading();wx.showToast({title:'网络错误',icon:'error'})}})}})},
  onSyncArtistMetadata(){if(this.data.metadataSyncing)return;wx.showModal({title:'同步艺人资料',content:'同步头像、主页背景、粉丝数、专辑数和简介。',confirmText:'开始同步',confirmColor:'#C94E25',success:r=>{if(!r.confirm)return;this.setData({metadataSyncing:true});wx.showLoading({title:'同步中…',mask:true});wx.cloud.callFunction({name:'syncArtistMetadata',data:{},success:(res:any)=>{wx.hideLoading();this.setData({metadataSyncing:false});const x=res&&res.result||{};if(x.success)wx.showModal({title:'同步完成',content:`扫描 ${x.scanned||0} 位，更新 ${x.updated||0} 位，跳过 ${x.skipped||0} 位，错误 ${x.errors||0} 位。`,showCancel:false});else wx.showToast({title:x.error||'同步失败',icon:'none'})},fail:()=>{wx.hideLoading();this.setData({metadataSyncing:false});wx.showToast({title:'网络错误',icon:'error'})}})}})},
  onScheduleToggle(e:WechatMiniprogram.SwitchChange){const enabled=e.detail.value;this.setData({crawlerScheduleEnabled:enabled});wx.cloud.callFunction({name:'crawlerControl',data:{action:'updateSchedule',enabled,interval:this.data.crawlerScheduleInterval}})},
  onScheduleInterval(e:WechatMiniprogram.TouchEvent){const interval=(e.currentTarget.dataset as any).v as 'daily'|'weekly';this.setData({crawlerScheduleInterval:interval});wx.cloud.callFunction({name:'crawlerControl',data:{action:'updateSchedule',enabled:this.data.crawlerScheduleEnabled,interval}})},
})