let timer:any=null
const status={status:'idle',mode:'',param:'',completedAt:'',log:[],progress:{totalArtists:0,processedArtists:0},lastRunSummary:{newAlbums:0,newCandidates:0}}
Page({
 data:{statusBarHeight:20,topbarHeight:64,crawlerStatus:status as any,crawlerTriggering:false,crawlerScheduleEnabled:false,crawlerScheduleInterval:'weekly',metadataSyncing:false,crawlerMode:'approved',crawlerParam:'',crawlerProgressPct:0,crawlerNeedsId:false,crawlerIsCloud:true,crawlerPlaceholder:'',crawlerDesc:'云端一键爬取所有已批准 rapper 的全部专辑 + 单曲',crawlerLastLog:'',crawlerTriggerTime:0,crawlerModes:[{key:'approved',label:'全部已批准',desc:'云端一键爬取所有已批准 rapper 的全部专辑 + 单曲',needsId:false,cloud:true,placeholder:''},{key:'artist',label:'按艺人ID',desc:'云端收录指定网易云艺人的全部专辑',needsId:true,cloud:true,placeholder:'网易云艺人 ID'},{key:'album',label:'按专辑ID',desc:'云端精确收录单张网易云专辑',needsId:true,cloud:true,placeholder:'网易云专辑 ID'}]},
 onLoad(){const a=getApp<IAppOption>();this.setData({statusBarHeight:a.globalData.statusBarHeight,topbarHeight:a.globalData.topbarHeight})},
 onShow(){this.poll()},onHide(){this.stop()},onUnload(){this.stop()},onBack(){wx.navigateBack()},
 poll(){this.stop();this.fetch();timer=setInterval(()=>this.fetch(),3000)},stop(){if(timer){clearInterval(timer);timer=null}},
 fetch(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'getStatus'},success:(r:any)=>{const x=r&&r.result&&r.result.status;if(!x)return;const p=x.progress||{};const safe=Object.assign({},status,x,{log:Array.isArray(x.log)?x.log:[],progress:Object.assign({},status.progress,p),lastRunSummary:Object.assign({},status.lastRunSummary,x.lastRunSummary||{})});this.setData({crawlerStatus:safe,crawlerProgressPct:p.totalArtists?Math.round((p.processedArtists||0)/(p.totalArtists||1)*100):0,crawlerScheduleEnabled:!!(x.schedule&&x.schedule.enabled),crawlerScheduleInterval:(x.schedule&&x.schedule.interval)||'weekly'})}})},
 onCrawlerModeTap(e:any){const k=e.currentTarget.dataset.key;const m=(this.data.crawlerModes as any[]).find(x=>x.key===k);if(m)this.setData({crawlerMode:k,crawlerNeedsId:m.needsId,crawlerIsCloud:m.cloud,crawlerPlaceholder:m.placeholder,crawlerDesc:m.desc,crawlerParam:''})},
 onCrawlerParamInput(e:any){this.setData({crawlerParam:e.detail.value||''})},
 onCrawlerTrigger(){const m=this.data.crawlerMode,p=(this.data.crawlerParam||'').trim();if((m==='artist'||m==='album')&&!/^\d+$/.test(p)){wx.showToast({title:'请输入数字 ID',icon:'none'});return}this.setData({crawlerTriggering:true});wx.cloud.callFunction({name:'cloudCrawler',data:{action:m==='approved'?'allApproved':m,param:p},success:()=>{this.setData({crawlerTriggering:false});this.fetch()},fail:()=>{this.setData({crawlerTriggering:false});wx.showToast({title:'启动失败',icon:'none'})}})},
 onCrawlerAbort(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'abort'},success:()=>this.fetch()})},
 onCrawlerClearLog(){wx.cloud.callFunction({name:'crawlerControl',data:{action:'clearLog'},success:()=>this.fetch()})},
 onCleanupSingles(){},onSyncArtistMetadata(){},onScheduleToggle(){},onScheduleInterval(){}
})