interface AlbumCard { id:string; title:string; artist:string; primaryArtist:string; neteaseArtistId:string; year:number; releaseDate:string; releaseDisplay:string; score:number; genres:string[]; scoreFill:string; coverUrl:string }
interface ArtistCard { id:string; artistId:string; artistName:string; picUrl:string; albumSize:number; fansSize:number; letter:string; brand?:string; brands?:string[] }
interface BrandCard { name:string; count:number }
interface ArtistLetterGroup { letter:string; list:ArtistCard[] }
const YEARS=[{name:'全部'},{name:'2026'},{name:'2025'},{name:'2024'},{name:'2023'},{name:'2022'},{name:'2021'},{name:'2020'},{name:'2019'},{name:'2018'},{name:'2010s'},{name:'2000s'}]
const MONTHS=['01','02','03','04','05','06','07','08','09','10','11','12']
const ALBUM_PAGE_SIZE=100
const LETTER_ORDER='ABCDEFGHIJKLMNOPQRSTUVWXYZ#'
function formatReleaseDate(value:any,year:number){if(!value)return year?String(year):'';const raw=typeof value==='string'?value:new Date(value).toISOString();const m=raw.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);return m?`${m[1]}.${m[2]}.${m[3]}`:year?String(year):''}
function mapAlbum(a:any):AlbumCard{const score=a.avgScore||0,year=a.releaseYear||0;return{id:a._id,title:a.title||'',artist:a.artist||'',primaryArtist:a.primaryArtist||(a.artist||'').split(/[,，&]/)[0].trim(),neteaseArtistId:String(a.neteaseArtistId||''),year,releaseDate:a.releaseDate||'',releaseDisplay:formatReleaseDate(a.releaseDate,year),score:Math.round(score*10)/10,genres:a.genres||[],scoreFill:Math.round(score/10*100)+'%',coverUrl:a.coverUrl||''}}
function alphaSort(a:ArtistCard,b:ArtistCard){return String(a.artistName||'').localeCompare(String(b.artistName||''),'zh-Hans-CN-u-co-pinyin',{sensitivity:'base',numeric:true})}
function buildLetterGroups(list:ArtistCard[]):ArtistLetterGroup[]{const bucket:Record<string,ArtistCard[]>={};list.forEach(a=>{const letter=(a.letter||'#').toUpperCase();if(!bucket[letter])bucket[letter]=[];bucket[letter].push(a)});return Object.keys(bucket).sort((a,b)=>LETTER_ORDER.indexOf(a)-LETTER_ORDER.indexOf(b)).map(letter=>({letter,list:bucket[letter]}))}
function albumSortByYear(year:string){return year==='全部'?'allMixed':'releaseYear'}
let _searchTimer:any=null
Page({
 data:{statusBarHeight:20,topbarHeight:64,keyword:'',viewMode:'albums' as 'albums'|'artists',years:YEARS,months:MONTHS,activeYear:'全部',activeMonth:'',list:[] as AlbumCard[],total:0,loading:false,loadingMore:false,albumPage:1,albumHasMore:true,albumKeyword:'',artistList:[] as ArtistCard[],artistVisibleList:[] as ArtistCard[],artistLetterGroups:[] as ArtistLetterGroup[],artistLetters:[] as string[],artistScrollIntoView:'',activeLetter:'',brandCards:[] as BrandCard[],artistTotal:0,artistLoading:false,artistKeyword:'',activeBrand:'全部'},
 onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight});this._fetchAlbums({pageSize:ALBUM_PAGE_SIZE,sortBy:'allMixed'},true);this._fetchArtists('')},
 onShow(){if(typeof this.getTabBar==='function')this.getTabBar()?.setData({selected:2})},
 _albumParams(page:number){const year=this.data.activeYear;return{keyword:this.data.keyword.trim()||undefined,year:year==='全部'?undefined:year,month:this.data.activeMonth||undefined,page,pageSize:ALBUM_PAGE_SIZE,sortBy:albumSortByYear(year)}},
 _fetchAlbums(params:Record<string,any>,reset=true){const albumKeyword=String(params.keyword||'');if(reset)this.setData({loading:true,loadingMore:false,albumPage:1,albumHasMore:true,list:[],albumKeyword});else this.setData({loadingMore:true});wx.cloud.callFunction({name:'getAlbums',data:params,success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({loading:false,loadingMore:false});return};const incoming=(r.list||[]).map(mapAlbum);const list=reset?incoming:this.data.list.concat(incoming);const total=Number(r.total||list.length),page=Number(r.page||params.page||1);this.setData({list,total,albumPage:page,albumHasMore:list.length<total&&incoming.length>0,loading:false,loadingMore:false})},fail:()=>this.setData({loading:false,loadingMore:false})} as any)},
 onAlbumScrollToLower(){if(this.data.viewMode!=='albums'||this.data.loading||this.data.loadingMore||!this.data.albumHasMore)return;this._fetchAlbums(this._albumParams(this.data.albumPage+1),false)},
 _renderArtistGrid(){const brand=this.data.activeBrand;const artistVisibleList=(brand==='全部'?this.data.artistList:this.data.artistList.filter(x=>(x.brands||[x.brand||'']).indexOf(brand)>=0)).slice();if(brand==='全部'){artistVisibleList.sort(alphaSort);const artistLetterGroups=buildLetterGroups(artistVisibleList);this.setData({artistVisibleList,artistLetterGroups,artistLetters:artistLetterGroups.map(g=>g.letter),artistTotal:artistVisibleList.length,activeLetter:'',artistScrollIntoView:''})}else{artistVisibleList.sort((a,b)=>{const diff=Number(b.albumSize||0)-Number(a.albumSize||0);return diff||alphaSort(a,b)});this.setData({artistVisibleList,artistLetterGroups:[],artistLetters:[],artistTotal:artistVisibleList.length,activeLetter:'',artistScrollIntoView:''})}},
 _fetchArtists(keyword=''){const artistKeyword=String(keyword||'').trim();this.setData({artistLoading:true,artistKeyword});wx.cloud.callFunction({name:'getArtists',data:{keyword:artistKeyword,limit:1000},success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({artistLoading:false});return};const artistList=(r.list||[]) as ArtistCard[];const counts:Record<string,number>={};artistList.forEach(a=>{const tags=a.brands&&a.brands.length?a.brands:(a.brand?[a.brand]:[]);tags.forEach(tag=>{counts[tag]=(counts[tag]||0)+1})});const brandCards:[BrandCard,...BrandCard[]]=[{name:'全部',count:artistList.length},...Object.keys(counts).sort((a,b)=>a.localeCompare(b,'zh-Hans-CN')).map(name=>({name,count:counts[name]}))];this.setData({artistList,brandCards,artistLoading:false},()=>this._renderArtistGrid())},fail:()=>this.setData({artistLoading:false})} as any)},
 onViewModeTap(e:WechatMiniprogram.TouchEvent){const mode=(e.currentTarget.dataset as any).mode as 'albums'|'artists';if(mode===this.data.viewMode)return;const kw=this.data.keyword.trim();this.setData({viewMode:mode});if(mode==='artists'){this.setData({activeBrand:'全部'});if(this.data.artistKeyword!==kw)this._fetchArtists(kw);else this._renderArtistGrid();return}if(this.data.albumKeyword!==kw)this._fetchAlbums(this._albumParams(1),true)},
 onSearch(e:WechatMiniprogram.Input){const keyword=e.detail.value;this.setData({keyword});if(_searchTimer)clearTimeout(_searchTimer);_searchTimer=setTimeout(()=>{const kw=this.data.keyword.trim();if(this.data.viewMode==='artists'){this.setData({activeBrand:'全部'});this._fetchArtists(kw);return}this._fetchAlbums(this._albumParams(1),true)},350)},
 onYearTap(e:WechatMiniprogram.TouchEvent){const year=(e.currentTarget.dataset as any).year;this.setData({activeYear:year,activeMonth:''});this._fetchAlbums({keyword:this.data.keyword.trim()||undefined,year:year==='全部'?undefined:year,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:albumSortByYear(year)},true)},
 onMonthTap(e:WechatMiniprogram.TouchEvent){if(!/^\d{4}$/.test(this.data.activeYear)){wx.showToast({title:'请选择具体年份',icon:'none'});return};const month=(e.currentTarget.dataset as any).month,active=this.data.activeMonth===month?'':month;this.setData({activeMonth:active});this._fetchAlbums({keyword:this.data.keyword.trim()||undefined,year:this.data.activeYear,month:active||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'},true)},
 onBrandTap(e:WechatMiniprogram.TouchEvent){const brand=(e.currentTarget.dataset as any).brand||'全部';this.setData({activeBrand:brand},()=>this._renderArtistGrid())},
 onLetterTap(e:WechatMiniprogram.TouchEvent){const letter=(e.currentTarget.dataset as any).letter;if(!letter)return;this.setData({activeLetter:letter,artistScrollIntoView:`artist-letter-${letter==='#'?'num':letter}`})},
 onAlbumTap(e:WechatMiniprogram.TouchEvent){const id=(e.currentTarget.dataset as any).id;wx.navigateTo({url:`/pages/album-detail/index?id=${id}`})},
 onArtistTap(e:WechatMiniprogram.TouchEvent){const ds=e.currentTarget.dataset as any;if(!ds.artistId)return;wx.navigateTo({url:`/pages/artist/index?artistId=${ds.artistId}&artistName=${encodeURIComponent(ds.artist)}`})}
})