import ARTIST_BRAND_MAP from '../../data/artistBrandMap'

interface AlbumCard { id:string; title:string; artist:string; primaryArtist:string; neteaseArtistId:string; year:number; releaseDate:string; releaseDisplay:string; score:number; genres:string[]; scoreFill:string; coverUrl:string }
interface ArtistCard { id:string; artistId:string; artistName:string; picUrl:string; albumSize:number; fansSize:number; letter:string; brand:string }
interface ArtistGroup { letter:string; list:ArtistCard[] }
const YEARS=[{name:'2026'},{name:'2025'},{name:'2024'},{name:'2023'},{name:'2022'},{name:'2021'},{name:'2020'},{name:'2019'},{name:'2018'},{name:'2010s'},{name:'2000s'}]
const MONTHS=['01','02','03','04','05','06','07','08','09','10','11','12']
const LETTER_ORDER='ABCDEFGHIJKLMNOPQRSTUVWXYZ#', ALBUM_PAGE_SIZE=100
function formatReleaseDate(value:any,year:number){if(!value)return year?String(year):'';const raw=typeof value==='string'?value:new Date(value).toISOString();const m=raw.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);return m?`${m[1]}.${m[2]}.${m[3]}`:year?String(year):''}
function mapAlbum(a:any):AlbumCard{const score=a.avgScore||0,year=a.releaseYear||0;return{id:a._id,title:a.title||'',artist:a.artist||'',primaryArtist:a.primaryArtist||(a.artist||'').split(/[,，&]/)[0].trim(),neteaseArtistId:String(a.neteaseArtistId||''),year,releaseDate:a.releaseDate||'',releaseDisplay:formatReleaseDate(a.releaseDate,year),score:Math.round(score*10)/10,genres:a.genres||[],scoreFill:Math.round(score/10*100)+'%',coverUrl:a.coverUrl||''}}
function letterRank(l:string){const i=LETTER_ORDER.indexOf(l||'#');return i>=0?i:LETTER_ORDER.length-1}
function groupArtists(list:ArtistCard[]):ArtistGroup[]{const m:Record<string,ArtistCard[]>={};list.forEach(a=>{const k=a.letter||'#';if(!m[k])m[k]=[];m[k].push(a)});return Object.keys(m).sort((a,b)=>letterRank(a)-letterRank(b)).map(letter=>({letter,list:m[letter]}))}
let _searchTimer:any=null
Page({
 data:{statusBarHeight:20,topbarHeight:64,keyword:'',viewMode:'albums' as 'albums'|'artists',years:YEARS,months:MONTHS,activeYear:'2026',activeMonth:'',list:[] as AlbumCard[],total:0,loading:false,loadingMore:false,albumPage:1,albumHasMore:true,artistList:[] as ArtistCard[],artistFilteredList:[] as ArtistCard[],artistGroups:[] as ArtistGroup[],artistLetters:[] as string[],artistTotal:0,artistLoading:false,artistScrollIntoView:'',activeLetter:'',brandOptions:[] as string[],activeBrand:'全部'},
 onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight});this._fetchAlbums({year:'2026',pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'},true);this._fetchArtists()},
 onShow(){if(typeof this.getTabBar==='function')this.getTabBar()?.setData({selected:2})},
 _albumParams(page:number){return{keyword:this.data.keyword.trim()||undefined,year:this.data.activeYear||undefined,month:this.data.activeMonth||undefined,page,pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'}},
 _fetchAlbums(params:Record<string,any>,reset=true){if(reset)this.setData({loading:true,loadingMore:false,albumPage:1,albumHasMore:true,list:[]});else this.setData({loadingMore:true});wx.cloud.callFunction({name:'getAlbums',data:params,success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({loading:false,loadingMore:false});return};const incoming=(r.list||[]).map(mapAlbum);const list=reset?incoming:this.data.list.concat(incoming);const total=Number(r.total||list.length),page=Number(r.page||params.page||1);this.setData({list,total,albumPage:page,albumHasMore:list.length<total&&incoming.length>0,loading:false,loadingMore:false})},fail:()=>this.setData({loading:false,loadingMore:false})} as any)},
 onAlbumScrollToLower(){if(this.data.viewMode!=='albums'||this.data.loading||this.data.loadingMore||!this.data.albumHasMore)return;this._fetchAlbums(this._albumParams(this.data.albumPage+1),false)},
 _applyArtistFilter(){const activeBrand=this.data.activeBrand;const filtered=activeBrand==='全部'?this.data.artistList:this.data.artistList.filter(a=>a.brand===activeBrand);const artistGroups=groupArtists(filtered);this.setData({artistFilteredList:filtered,artistGroups,artistLetters:artistGroups.map(g=>g.letter),artistTotal:filtered.length,activeLetter:'',artistScrollIntoView:''})},
 _fetchArtists(keyword=''){this.setData({artistLoading:true});wx.cloud.callFunction({name:'getArtists',data:{keyword,limit:1000},success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({artistLoading:false});return};const artistList=((r.list||[]) as any[]).map(a=>({...a,brand:ARTIST_BRAND_MAP[String(a.artistId)]||'未归类'})) as ArtistCard[];const brandOptions=['全部',...Array.from(new Set(artistList.map(a=>a.brand).filter(b=>b&&b!=='未归类'))).sort((a,b)=>a.localeCompare(b,'zh-Hans-CN'))];this.setData({artistList,brandOptions,artistLoading:false},()=>this._applyArtistFilter())},fail:()=>this.setData({artistLoading:false})} as any)},
 onViewModeTap(e:WechatMiniprogram.TouchEvent){const mode=(e.currentTarget.dataset as any).mode;if(mode===this.data.viewMode)return;this.setData({viewMode:mode})},
 onSearch(e:WechatMiniprogram.Input){const keyword=e.detail.value;this.setData({keyword});if(_searchTimer)clearTimeout(_searchTimer);_searchTimer=setTimeout(()=>{const kw=keyword.trim();if(this.data.viewMode==='artists'){this.setData({activeBrand:'全部'});this._fetchArtists(kw);return}this._fetchAlbums({keyword:kw||undefined,year:this.data.activeYear||undefined,month:this.data.activeMonth||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'},true)},400)},
 onYearTap(e:WechatMiniprogram.TouchEvent){const year=(e.currentTarget.dataset as any).year,active=this.data.activeYear===year?'':year;this.setData({activeYear:active,activeMonth:''});this._fetchAlbums({keyword:this.data.keyword.trim()||undefined,year:active||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'},true)},
 onMonthTap(e:WechatMiniprogram.TouchEvent){if(!/^\d{4}$/.test(this.data.activeYear)){wx.showToast({title:'请选择具体年份',icon:'none'});return};const month=(e.currentTarget.dataset as any).month,active=this.data.activeMonth===month?'':month;this.setData({activeMonth:active});this._fetchAlbums({keyword:this.data.keyword.trim()||undefined,year:this.data.activeYear,month:active||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:'releaseYear'},true)},
 onBrandTap(e:WechatMiniprogram.TouchEvent){const brand=(e.currentTarget.dataset as any).brand||'全部';if(brand===this.data.activeBrand)return;this.setData({activeBrand:brand},()=>this._applyArtistFilter())},
 onLetterTap(e:WechatMiniprogram.TouchEvent){const l=(e.currentTarget.dataset as any).letter;if(!l)return;this.setData({activeLetter:l,artistScrollIntoView:`artist-letter-${l==='#'?'num':l}`})},
 onAlbumTap(e:WechatMiniprogram.TouchEvent){const id=(e.currentTarget.dataset as any).id;wx.navigateTo({url:`/pages/album-detail/index?id=${id}`})},
 onArtistTap(e:WechatMiniprogram.TouchEvent){const ds=e.currentTarget.dataset as any;if(!ds.artistId)return;wx.navigateTo({url:`/pages/artist/index?artistId=${ds.artistId}&artistName=${encodeURIComponent(ds.artist)}`})}
})