interface AlbumCard { id:string; title:string; artist:string; primaryArtist:string; neteaseArtistId:string; year:number; releaseDate:string; releaseDisplay:string; score:number; reviewCount:number; genres:string[]; scoreFill:string; coverUrl:string }
interface AlbumLetterGroup { letter:string; list:AlbumCard[] }
interface ArtistCard { id:string; artistId:string; artistName:string; picUrl:string; albumSize:number; fansSize:number; letter:string; brand?:string; brands?:string[] }
interface BrandCard { name:string; count:number }
interface ArtistLetterGroup { letter:string; list:ArtistCard[] }
const YEARS=[{name:'ALL'},{name:'2026'},{name:'2025'},{name:'2024'},{name:'2023'},{name:'2022'},{name:'2021'},{name:'2020'},{name:'2019'},{name:'2018'},{name:'2010s'},{name:'2000s'}]
const MONTHS=['01','02','03','04','05','06','07','08','09','10','11','12']
const ALBUM_PAGE_SIZE=100
const LETTER_ORDER='ABCDEFGHIJKLMNOPQRSTUVWXYZ#'
const ALBUM_LETTERS=LETTER_ORDER.split('')
function isAllYear(year:string){return year==='ALL'}
function formatReleaseDate(value:any,year:number){if(!value)return year?String(year):'';const raw=typeof value==='string'?value:new Date(value).toISOString();const m=raw.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:year?String(year):''}
function mapAlbum(a:any):AlbumCard{const score=a.avgScore||0,year=a.releaseYear||0;return{id:a._id,title:a.title||'',artist:a.artist||'',primaryArtist:a.primaryArtist||(a.artist||'').split(/[,，&]/)[0].trim(),neteaseArtistId:String(a.neteaseArtistId||''),year,releaseDate:a.releaseDate||'',releaseDisplay:formatReleaseDate(a.releaseDate,year),score:Math.round(score*10)/10,reviewCount:Number(a.reviewCount||0),genres:a.genres||[],scoreFill:Math.round(score/10*100)+'%',coverUrl:a.coverUrl||''}}
function alphaSort(a:ArtistCard,b:ArtistCard){return String(a.artistName||'').localeCompare(String(b.artistName||''),'zh-Hans-CN-u-co-pinyin',{sensitivity:'base',numeric:true})}
function albumAlphaSort(a:AlbumCard,b:AlbumCard){const t=String(a.title||'').localeCompare(String(b.title||''),'zh-Hans-CN-u-co-pinyin',{sensitivity:'base',numeric:true});return t||String(b.releaseDate||'').localeCompare(String(a.releaseDate||''))}
function scoredSort(a:AlbumCard,b:AlbumCard){return(b.score-a.score)||String(b.releaseDate||'').localeCompare(String(a.releaseDate||''))}
function releaseSort(a:AlbumCard,b:AlbumCard){return String(b.releaseDate||'').localeCompare(String(a.releaseDate||''))||String(a.title||'').localeCompare(String(b.title||''),'zh-Hans-CN-u-co-pinyin',{sensitivity:'base',numeric:true})}
function letterOfTitle(title:string){const c=String(title||'').trim().charAt(0).toUpperCase();return /^[A-Z]$/.test(c)?c:'#'}
function buildLetterGroups(list:ArtistCard[]):ArtistLetterGroup[]{const bucket:Record<string,ArtistCard[]>={};list.forEach(a=>{const letter=(a.letter||'#').toUpperCase();if(!bucket[letter])bucket[letter]=[];bucket[letter].push(a)});return Object.keys(bucket).sort((a,b)=>LETTER_ORDER.indexOf(a)-LETTER_ORDER.indexOf(b)).map(letter=>({letter,list:bucket[letter]}))}
function buildAlbumLetterGroups(list:AlbumCard[]):AlbumLetterGroup[]{const bucket:Record<string,AlbumCard[]>={};list.forEach(a=>{const letter=letterOfTitle(a.title);if(!bucket[letter])bucket[letter]=[];bucket[letter].push(a)});return Object.keys(bucket).sort((a,b)=>LETTER_ORDER.indexOf(a)-LETTER_ORDER.indexOf(b)).map(letter=>({letter,list:bucket[letter].slice().sort(albumAlphaSort)}))}
let _searchTimer:any=null
let _blurTimer:any=null
Page({
 data:{statusBarHeight:20,topbarHeight:64,keyword:'',viewMode:'albums' as 'albums'|'artists',suggestionVisible:false,suggestionLoading:false,albumSuggestions:[] as AlbumCard[],artistSuggestions:[] as ArtistCard[],years:YEARS,months:MONTHS,activeYear:'2026',activeMonth:'',list:[] as AlbumCard[],yearRatedList:[] as AlbumCard[],yearUnratedList:[] as AlbumCard[],allRatedList:[] as AlbumCard[],allUnratedGroups:[] as AlbumLetterGroup[],allAlbumLetters:ALBUM_LETTERS,activeAlbumLetter:'',total:0,loading:false,loadingMore:false,albumPage:1,albumHasMore:true,albumKeyword:'',artistList:[] as ArtistCard[],artistVisibleList:[] as ArtistCard[],artistLetterGroups:[] as ArtistLetterGroup[],artistLetters:[] as string[],artistScrollIntoView:'',activeLetter:'',brandCards:[] as BrandCard[],artistTotal:0,artistLoading:false,artistKeyword:'',activeBrand:'全部'},
 onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight});this._fetchAlbums({year:'2026',pageSize:ALBUM_PAGE_SIZE,sortBy:'yearRatedFirst'},true);this._fetchArtists('')},
 onShow(){if(typeof this.getTabBar==='function')this.getTabBar()?.setData({selected:2})},
 _albumParams(page:number){const year=this.data.activeYear;return{year:isAllYear(year)?'ALL':year||undefined,month:isAllYear(year)?undefined:this.data.activeMonth||undefined,page,pageSize:ALBUM_PAGE_SIZE,sortBy:isAllYear(year)?'allRatedFirst':'yearRatedFirst'}},
 _updateAlbumSections(list:AlbumCard[]){const rated=list.filter(a=>a.score>0).slice().sort(scoredSort),unrated=list.filter(a=>!(a.score>0));if(isAllYear(this.data.activeYear)){const allUnratedGroups=this.data.activeAlbumLetter?[{letter:this.data.activeAlbumLetter,list:unrated.slice().sort(albumAlphaSort)}]:buildAlbumLetterGroups(unrated);this.setData({yearRatedList:[],yearUnratedList:[],allRatedList:rated,allUnratedGroups,allAlbumLetters:ALBUM_LETTERS});return}this.setData({yearRatedList:rated,yearUnratedList:unrated.slice().sort(releaseSort),allRatedList:[],allUnratedGroups:[],allAlbumLetters:ALBUM_LETTERS,activeAlbumLetter:''})},
 _fetchAlbums(params:Record<string,any>,reset=true){const albumKeyword=String(params.keyword||'');if(reset)this.setData({loading:true,loadingMore:false,albumPage:1,albumHasMore:true,list:[],yearRatedList:[],yearUnratedList:[],albumKeyword,artistScrollIntoView:''});else this.setData({loadingMore:true});wx.cloud.callFunction({name:'getAlbums',data:params,success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({loading:false,loadingMore:false});return};const incoming=(r.list||[]).map(mapAlbum);const list=reset?incoming:this.data.list.concat(incoming);const total=Number(r.total||list.length),page=Number(r.page||params.page||1);this.setData({list,total,albumPage:page,albumHasMore:list.length<total&&incoming.length>0,loading:false,loadingMore:false},()=>this._updateAlbumSections(list))},fail:()=>this.setData({loading:false,loadingMore:false})} as any)},
 _fetchUnratedByLetter(letter:string){if(!isAllYear(this.data.activeYear))return;this.setData({activeAlbumLetter:letter,loadingMore:true});wx.cloud.callFunction({name:'getAlbums',data:{year:'ALL',unratedLetter:letter,page:1,pageSize:100},success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({loadingMore:false});return}const albums=(r.list||[]).map(mapAlbum).slice().sort(albumAlphaSort);this.setData({allUnratedGroups:[{letter,list:albums}],loadingMore:false,artistScrollIntoView:`album-letter-${letter==='#'?'num':letter}`})},fail:()=>this.setData({loadingMore:false})} as any)},
 onAlbumScrollToLower(){if(this.data.viewMode!=='albums'||this.data.loading||this.data.loadingMore||!this.data.albumHasMore)return;this._fetchAlbums(this._albumParams(this.data.albumPage+1),false)},
 _renderArtistGrid(){const brand=this.data.activeBrand;const artistVisibleList=(brand==='全部'?this.data.artistList:this.data.artistList.filter(x=>(x.brands||[x.brand||'']).indexOf(brand)>=0)).slice();if(brand==='全部'){artistVisibleList.sort(alphaSort);const artistLetterGroups=buildLetterGroups(artistVisibleList);this.setData({artistVisibleList,artistLetterGroups,artistLetters:artistLetterGroups.map(g=>g.letter),artistTotal:artistVisibleList.length,activeLetter:'',artistScrollIntoView:''})}else{artistVisibleList.sort((a,b)=>Number(b.albumSize||0)-Number(a.albumSize||0)||alphaSort(a,b));this.setData({artistVisibleList,artistLetterGroups:[],artistLetters:[],artistTotal:artistVisibleList.length,activeLetter:'',artistScrollIntoView:''})}},
 _fetchArtists(keyword=''){const artistKeyword=String(keyword||'').trim();this.setData({artistLoading:true,artistKeyword});wx.cloud.callFunction({name:'getArtists',data:{keyword:artistKeyword,limit:1000},success:(res:any)=>{const r=res.result||{};if(!r.success){this.setData({artistLoading:false});return};const artistList=(r.list||[]) as ArtistCard[];const counts:Record<string,number>={};artistList.forEach(a=>{const tags=a.brands&&a.brands.length?a.brands:(a.brand?[a.brand]:[]);tags.forEach(tag=>{counts[tag]=(counts[tag]||0)+1})});const brandCards:[BrandCard,...BrandCard[]]=[{name:'全部',count:artistList.length},...Object.keys(counts).sort((a,b)=>a.localeCompare(b,'zh-Hans-CN')).map(name=>({name,count:counts[name]}))];this.setData({artistList,brandCards,artistLoading:false},()=>this._renderArtistGrid())},fail:()=>this.setData({artistLoading:false})} as any)},
 _fetchSuggestions(keyword:string){const kw=String(keyword||'').trim();if(!kw){this.setData({suggestionVisible:false,suggestionLoading:false,albumSuggestions:[],artistSuggestions:[]});return}this.setData({suggestionVisible:true,suggestionLoading:true});if(this.data.viewMode==='artists'){wx.cloud.callFunction({name:'getArtists',data:{keyword:kw,limit:8},success:(res:any)=>{const r=res.result||{};this.setData({artistSuggestions:r.success?(r.list||[]).slice(0,8):[],albumSuggestions:[],suggestionLoading:false})},fail:()=>this.setData({artistSuggestions:[],suggestionLoading:false})} as any);return}wx.cloud.callFunction({name:'getAlbums',data:{keyword:kw,page:1,pageSize:8,sortBy:'relevance'},success:(res:any)=>{const r=res.result||{};this.setData({albumSuggestions:r.success?(r.list||[]).map(mapAlbum).slice(0,8):[],artistSuggestions:[],suggestionLoading:false})},fail:()=>this.setData({albumSuggestions:[],suggestionLoading:false})} as any)},
 onViewModeTap(e:WechatMiniprogram.TouchEvent){const mode=(e.currentTarget.dataset as any).mode as 'albums'|'artists';if(mode===this.data.viewMode)return;this.setData({viewMode:mode,artistScrollIntoView:''},()=>{if(this.data.keyword.trim())this._fetchSuggestions(this.data.keyword)})},
 onSearchFocus(){if(_blurTimer)clearTimeout(_blurTimer);if(this.data.keyword.trim())this.setData({suggestionVisible:true})},onSearchBlur(){_blurTimer=setTimeout(()=>this.setData({suggestionVisible:false}),180)},onSearch(e:WechatMiniprogram.Input){this.setData({keyword:e.detail.value});if(_searchTimer)clearTimeout(_searchTimer);_searchTimer=setTimeout(()=>this._fetchSuggestions(this.data.keyword),160)},
 onSuggestionAlbumTap(e:WechatMiniprogram.TouchEvent){const id=String((e.currentTarget.dataset as any).id||'');if(id)wx.navigateTo({url:`/pages/album-detail/index?id=${id}`})},onSuggestionArtistTap(e:WechatMiniprogram.TouchEvent){const ds=e.currentTarget.dataset as any;if(ds.artistId)wx.navigateTo({url:`/pages/artist/index?artistId=${ds.artistId}&artistName=${encodeURIComponent(ds.artist||'')}`})},
 onSubmitAlbumRequest(){wx.navigateTo({url:'/pages/album-submit/index'})},
 onSubmitArtistRequest(){wx.showModal({title:'提交 rapper',editable:true,placeholderText:'输入网易云 rapper 名称',confirmText:'提交',confirmColor:'#C94E25',success:(modal:any)=>{const name=String(modal.content||'').trim();if(!modal.confirm||!name)return;wx.showLoading({title:'查询中…',mask:true});wx.cloud.callFunction({name:'submitArtistRequest',data:{name},success:(res:any)=>{wx.hideLoading();const r=res.result||{};if(!r.success){wx.showToast({title:r.error||'提交失败',icon:'none'});return}if(r.existed){wx.showToast({title:r.status==='approved'?'已收录':r.status==='pending'?'审核中':'已有记录',icon:'none'});return}wx.showToast({title:'已提交',icon:'success'})},fail:()=>{wx.hideLoading();wx.showToast({title:'提交失败',icon:'none'})}} as any)}})},
 onYearTap(e:WechatMiniprogram.TouchEvent){const year=(e.currentTarget.dataset as any).year,active=this.data.activeYear===year?'':year;this.setData({activeYear:active,activeMonth:'',activeAlbumLetter:'',artistScrollIntoView:''});this._fetchAlbums({year:isAllYear(active)?'ALL':active||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:isAllYear(active)?'allRatedFirst':'yearRatedFirst'},true)},onMonthTap(e:WechatMiniprogram.TouchEvent){if(!/^\d{4}$/.test(this.data.activeYear)){wx.showToast({title:'请选择具体年份',icon:'none'});return};const month=(e.currentTarget.dataset as any).month,active=this.data.activeMonth===month?'':month;this.setData({activeMonth:active});this._fetchAlbums({year:this.data.activeYear,month:active||undefined,page:1,pageSize:ALBUM_PAGE_SIZE,sortBy:'yearRatedFirst'},true)},
 onBrandTap(e:WechatMiniprogram.TouchEvent){this.setData({activeBrand:(e.currentTarget.dataset as any).brand||'全部'},()=>this._renderArtistGrid())},onLetterTap(e:WechatMiniprogram.TouchEvent){const letter=(e.currentTarget.dataset as any).letter;if(letter)this.setData({activeLetter:letter,artistScrollIntoView:`artist-letter-${letter==='#'?'num':letter}`})},onAlbumLetterTap(e:WechatMiniprogram.TouchEvent){const letter=(e.currentTarget.dataset as any).letter;if(letter)this._fetchUnratedByLetter(letter)},onAlbumTap(e:WechatMiniprogram.TouchEvent){wx.navigateTo({url:`/pages/album-detail/index?id=${(e.currentTarget.dataset as any).id}`})},onArtistTap(e:WechatMiniprogram.TouchEvent){const ds=e.currentTarget.dataset as any;if(ds.artistId)wx.navigateTo({url:`/pages/artist/index?artistId=${ds.artistId}&artistName=${encodeURIComponent(ds.artist)}`})}
})