const cloud=require('wx-server-sdk');const {isAdmin}=require('./_shared/auth');cloud.init({env:cloud.DYNAMIC_CURRENT_ENV});const db=cloud.database();const COL='review_reports';exports.main=async event=>{const{OPENID}=cloud.getWXContext(),action=event.action||'';if(!OPENID)return{success:false,error:'请先登录'};try{if(action==='deleteMine')return deleteMine(String(event.reviewId||''),OPENID);if(action==='report')return report(String(event.reviewId||''),String(event.reason||'').trim(),OPENID);if(!(await isAdmin(OPENID)))return{success:false,error:'unauthorized'};if(action==='list')return list();if(action==='stats')return stats();if(action==='decide')return decide(String(event.id||''),String(event.decision||''),OPENID);return{success:false,error:'unknown action'}}catch(e){return{success:false,error:e.message}}};async function getReview(id){if(!id)throw new Error('缺少评论ID');return(await db.collection('reviews').doc(id).get()).data}
// Recompute avgScore/reviewCount from every remaining review, excluding excludeId in JS (not via
// query) since combining _id with a command operator isn't reliably supported here and a where()
// right after remove() can still see the just-deleted doc.
async function recomputeAlbumScore(albumId,excludeId){let rows=[],skip=0;while(true){const page=await db.collection('reviews').where({albumId}).field({rating:true,_id:true}).skip(skip).limit(100).get();rows=rows.concat(page.data||[]);if(!page.data||page.data.length<100)break;skip+=100}if(excludeId)rows=rows.filter(r=>r._id!==excludeId);const sum=rows.reduce((t,x)=>t+(Number(x.rating)||0),0),count=rows.length;await db.collection('albums').doc(albumId).update({data:{avgScore:count?Math.round(sum/count*10)/10:0,reviewCount:count}})}
async function deleteReview(id){const review=await getReview(id).catch(()=>null);const albumId=review&&review.albumId;await db.collection('reviews').doc(id).remove();for(const col of['review_likes','review_replies']){const r=await db.collection(col).where({reviewId:id}).limit(100).get();for(const x of r.data||[])await db.collection(col).doc(x._id).remove()}if(albumId)await recomputeAlbumScore(albumId,id)}async function deleteMine(id,openId){const r=await getReview(id),owner=String(r.authorOpenId||r.userId||'');if(owner!==openId)return{success:false,error:'只能删除自己的评论'};await deleteReview(id);return{success:true}}async function ensureCollection(name){try{await db.collection(name).limit(1).get()}catch(e){if(!isCollectionMissing(e))throw e;try{await db.createCollection(name)}catch(x){if(!String(x&&(x.errMsg||x.message)||'').includes('already exists'))throw x}}}
function isCollectionMissing(e){const msg=String(e&&(e.errMsg||e.message)||'');return msg.includes('DATABASE_COLLECTION_NOT_EXIST')||msg.includes('collection not exists')||msg.includes('Db or Table not exist')}
async function report(id,reason,openId){const r=await getReview(id),owner=String(r.authorOpenId||r.userId||'');if(owner===openId)return{success:false,error:'自己的评论请直接删除'};await ensureCollection(COL);const old=await db.collection(COL).where({reviewId:id,reportedBy:openId,status:'pending'}).limit(1).get();if(old.data.length)return{success:true,existed:true};await db.collection(COL).add({data:{reviewId:id,albumId:String(r.albumId||''),albumTitle:String(r.albumTitle||''),reviewContent:String(r.content||''),reviewAuthorName:String(r.userNickName||'匿名用户'),reviewAuthorOpenId:owner,reason:reason||'不当言论',reportedBy:openId,status:'pending',submittedAt:db.serverDate(),decidedAt:null}});return{success:true}}async function list(){try{const r=await db.collection(COL).where({status:'pending'}).orderBy('submittedAt','desc').limit(100).get();return{success:true,list:r.data,total:r.data.length}}catch(e){if(isCollectionMissing(e))return{success:true,list:[],total:0};throw e}}async function stats(){try{const r=await db.collection(COL).where({status:'pending'}).count();return{success:true,pending:r.total}}catch(e){if(isCollectionMissing(e))return{success:true,pending:0};throw e}}async function decide(id,decision,openId){if(!id||!['keep','delete'].includes(decision))return{success:false,error:'invalid decision'};const item=(await db.collection(COL).doc(id).get()).data;if(!item)return{success:false,error:'举报不存在'};if(decision==='delete'){try{await deleteReview(String(item.reviewId||''))}catch(e){}}await db.collection(COL).doc(id).update({data:{status:decision==='delete'?'deleted':'kept',decision,decidedAt:db.serverDate(),decidedBy:openId}});if(item.reportedBy)await notify(item.reportedBy,{type:'report_result',message:`你举报的评论已${decision==='delete'?'被删除':'审核后予以保留'}（《${item.albumTitle||'专辑'}》）`,albumId:item.albumId||''});return{success:true}}
// Best-effort — a notification failure should never block the moderation decision itself.
async function notify(recipientOpenId,data){try{await ensureCollection('notifications');await db.collection('notifications').add({data:{recipientOpenId,read:false,createdAt:db.serverDate(),...data}})}catch(e){}}