Page({
  data:{statusBarHeight:20,topbarHeight:64,mode:'search' as 'search'|'manual',searchName:'',searching:false,submitting:false,title:'',artist:'',releaseDate:'',company:'',description:'',tracksText:'',coverUrl:'',localCover:''},
  onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight})},
  onBack(){wx.navigateBack()},
  onInput(e:WechatMiniprogram.Input){const field=String((e.currentTarget.dataset as any).field||'');if(field)this.setData({[field]:e.detail.value} as any)},
  onSearch(){const name=String(this.data.searchName||'').trim();if(!name){wx.showToast({title:'请输入专辑名称',icon:'none'});return}this.setData({searching:true});wx.cloud.callFunction({name:'submitAlbumRequest',data:{action:'search',name},success:(res:any)=>{const r=res.result||{};this.setData({searching:false});if(!r.success){wx.showToast({title:r.error||'查询失败',icon:'none'});return}if(r.needsManual){this.setData({mode:'manual',title:name});wx.showToast({title:'网易云未找到，请手动补充',icon:'none'});return}if(r.existed){wx.showToast({title:r.status==='approved'?'该专辑已收录':r.status==='pending'?'该专辑审核中':'已有记录',icon:'none'});return}wx.showToast({title:'已从网易云提交',icon:'success'});setTimeout(()=>wx.navigateBack(),700)},fail:()=>{this.setData({searching:false});wx.showToast({title:'查询失败',icon:'none'})}} as any)},
  onManual(){this.setData({mode:'manual',title:String(this.data.searchName||'').trim()})},
  onChooseCover(){wx.chooseMedia({count:1,mediaType:['image'],sourceType:['album','camera'],success:(res:any)=>{const path=res.tempFiles&&res.tempFiles[0]&&res.tempFiles[0].tempFilePath;if(!path)return;this.setData({localCover:path});wx.showLoading({title:'上传封面…',mask:true});const ext=(path.split('.').pop()||'jpg').toLowerCase();const cloudPath=`album-submissions/${Date.now()}_${Math.random().toString(36).slice(2,8)}.${ext}`;wx.cloud.uploadFile({cloudPath,filePath:path,success:(up:any)=>{wx.hideLoading();this.setData({coverUrl:up.fileID})},fail:()=>{wx.hideLoading();wx.showToast({title:'封面上传失败',icon:'none'})}})}})},
  onSubmitManual(){const title=String(this.data.title||'').trim(),artist=String(this.data.artist||'').trim(),tracks=String(this.data.tracksText||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!title||!artist){wx.showToast({title:'请填写专辑名和歌手',icon:'none'});return}if(!this.data.coverUrl){wx.showToast({title:'请上传专辑封面',icon:'none'});return}if(!tracks.length){wx.showToast({title:'请至少填写一首曲目',icon:'none'});return}this.setData({submitting:true});wx.cloud.callFunction({name:'submitAlbumRequest',data:{action:'manual',title,artist,releaseDate:String(this.data.releaseDate||'').trim(),company:String(this.data.company||'').trim(),description:String(this.data.description||'').trim(),tracks,coverUrl:this.data.coverUrl},success:(res:any)=>{const r=res.result||{};this.setData({submitting:false});if(!r.success){wx.showToast({title:r.error||'提交失败',icon:'none'});return}if(r.existed){wx.showToast({title:'该专辑已在审核中',icon:'none'});return}wx.showToast({title:'已提交管理员审核',icon:'success'});setTimeout(()=>wx.navigateBack(),700)},fail:()=>{this.setData({submitting:false});wx.showToast({title:'提交失败',icon:'none'})}} as any)}
})