import { getThemeClass, getThemeMode, setThemeMode, toggleThemeMode } from '../../utils/theme'
import { logout } from '../../utils/auth'

interface ProfileReview {_id:string;albumId:string;albumTitle:string;ratingText:string;content:string;timeAgo:string;likes:number}
Page({
 data:{statusBarHeight:20,topbarHeight:64,themeClass:'',themeMode:'dark' as 'dark'|'light',isLoggedIn:false,userInfo:null as IAppOption['globalData']['userInfo'],isCritic:false,isAdmin:false,pendingCount:0,albumFlagCount:0,ownershipCorrectionCount:0,albumAdminCount:0,reportCount:0,favCount:0,albumCount:0,reviews:[] as ProfileReview[],loading:false},
 onLoad(){const app=getApp<IAppOption>();this.setData({statusBarHeight:app.globalData.statusBarHeight,topbarHeight:app.globalData.topbarHeight})},
 onShow(){if(typeof this.getTabBar==='function')this.getTabBar()?.setData({selected:4});this.setData({themeClass:getThemeClass(),themeMode:getThemeMode()});const app=getApp<IAppOption>();const loggedIn=!!app.globalData.userInfo;this.setData({isLoggedIn:loggedIn,userInfo:app.globalData.userInfo,isCritic:app.globalData.userType==='critic',isAdmin:app.globalData.isAdmin});if(loggedIn)this._loadReviews()},
 onToggleTheme(){const mode=toggleThemeMode();this.setData({themeClass:getThemeClass(),themeMode:mode})},
 _loadReviews(){this.setData({loading:true});wx.cloud.callFunction({name:'getUserInfo',success:(res:any)=>{const result=res.result;if(!result.success){this.setData({loading:false});return}const app=getApp<IAppOption>(),user=result.user;app.globalData.userInfo={openId:user.openId,nickName:user.nickName,avatarUrl:user.avatarUrl||'',type:user.type,bio:user.bio||'',reviewCount:user.reviewCount||0};app.globalData.userType=user.type;app.globalData.isAdmin=user.type==='admin';const isAdmin=user.type==='admin';this.setData({userInfo:app.globalData.userInfo,isCritic:user.type==='critic',isAdmin});if(isAdmin)this._loadPendingCount();wx.cloud.callFunction({name:'getReviews',data:{userId:user.openId,pageSize:20},success:(r:any)=>{const rv=r.result;const list=(rv.list||[]).map((item:any)=>({_id:item._id,albumId:item.albumId,albumTitle:item.albumTitle||item.albumId,ratingText:'★'.repeat(item.rating||0),content:item.content,timeAgo:item.timeAgo||'',likes:item.likes||0}));this.setData({reviews:list,albumCount:new Set(list.map((x:ProfileReview)=>x.albumId)).size,loading:false})},fail:()=>this.setData({loading:false})});wx.cloud.callFunction({name:'getFavorites',data:{},success:(fr:any)=>{if(fr.result?.success)this.setData({favCount:(fr.result.list||[]).length})}} as any)},fail:()=>this.setData({loading:false})})},
 _loadPendingCount(){wx.cloud.callFunction({name:'manageCandidates',data:{action:'stats'},success:(res:any)=>{const r=res.result;if(r.success)this.setData({pendingCount:r.pending||0})}});wx.cloud.callFunction({name:'manageAlbumCandidates',data:{action:'stats'},success:(res:any)=>{const r=res.result;if(r.success){const albumFlagCount=r.pending||0;this.setData({albumFlagCount,albumAdminCount:albumFlagCount+(this.data.ownershipCorrectionCount||0)})}}});wx.cloud.callFunction({name:'manageAlbumOwnershipCorrections',data:{action:'stats'},success:(res:any)=>{const r=res.result;if(r.success){const ownershipCorrectionCount=r.pending||0;this.setData({ownershipCorrectionCount,albumAdminCount:ownershipCorrectionCount+(this.data.albumFlagCount||0)})}}});wx.cloud.callFunction({name:'reviewModeration',data:{action:'stats'},success:(res:any)=>{const r=res.result;if(r.success)this.setData({reportCount:r.pending||0})}})},
 onAdminCandidates(){wx.navigateTo({url:'/pages/admin/index'})},onAdminAlbumFlags(){wx.navigateTo({url:'/pages/album-candidates/index'})},onAdminOwnershipCorrections(){wx.navigateTo({url:'/pages/ownership-corrections/index'})},onAdminReviewReports(){wx.navigateTo({url:'/pages/review-reports/index'})},onAdminTrackCorrections(){wx.navigateTo({url:'/pages/track-corrections/index'})},onAdminCrawlerReports(){wx.navigateTo({url:'/pages/crawler-reports/index'})},onAdminAlbums(){wx.navigateTo({url:'/pages/album-admin/index'})},onAdminHiddenAlbums(){wx.navigateTo({url:'/pages/hidden-albums/index'})},onAdminArtistBrands(){wx.navigateTo({url:'/pages/artist-brands/index'})},onAdminCrawler(){wx.navigateTo({url:'/pages/crawler/index'})},onAdminCritics(){wx.navigateTo({url:'/pages/critics/index'})},
 onMyReviews(){wx.navigateTo({url:'/pages/my-reviews/index'})},onMyLikes(){wx.navigateTo({url:'/pages/my-likes/index'})},onFeedback(){wx.navigateTo({url:'/pages/feedback/index'})},onCriticApplication(){wx.navigateTo({url:'/pages/critic-application/index'})},onMyFavorites(){wx.navigateTo({url:'/pages/favorites/index'})},onSettingsTap(){const current=getThemeMode();wx.showActionSheet({itemList:[current==='dark'?'✓ 深色模式':'深色模式',current==='light'?'✓ 浅色模式':'浅色模式'],success:(res)=>{const mode=res.tapIndex===0?'dark':'light';setThemeMode(mode);this.setData({themeClass:getThemeClass(),themeMode:mode});wx.showToast({title:mode==='dark'?'已切换深色模式':'已切换浅色模式',icon:'none'})}})},onEditWeChatProfile(){wx.navigateTo({url:'/pages/login/index'})},onLogout(){wx.showModal({title:'退出登录',content:'退出后仍会保留你的评论、评分和收藏记录。',confirmText:'退出',confirmColor:'#C94E25',success:(res)=>{if(!res.confirm)return;logout();this.setData({isLoggedIn:false,userInfo:null,isCritic:false,isAdmin:false,reviews:[],favCount:0,albumCount:0,pendingCount:0,albumFlagCount:0,ownershipCorrectionCount:0,albumAdminCount:0,reportCount:0});wx.showToast({title:'已退出登录',icon:'none'})}})},onLogin(){wx.navigateTo({url:'/pages/login/index'})},onReviewTap(e:WechatMiniprogram.TouchEvent){const id=(e.currentTarget.dataset as {id:string}).id;if(id)wx.navigateTo({url:`/pages/album-detail/index?id=${id}`})}
})